import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

const outputsPath = fileURLToPath(new URL('./amplify_outputs.json', import.meta.url))

/**
 * `amplify_outputs.json` is generated by Amplify (sandbox or pipeline deploy) and
 * is gitignored, so it may not exist at build time (e.g. a fresh clone). This
 * plugin lets the dynamic import in src/config.ts resolve to an empty config
 * instead of failing the build. When the file exists, the normal import is used.
 */
function optionalAmplifyOutputs(): Plugin {
  const virtualId = '\0virtual:amplify-outputs-empty'
  return {
    name: 'optional-amplify-outputs',
    resolveId(source, importer) {
      if (source.endsWith('amplify_outputs.json') && importer && !existsSync(outputsPath)) {
        return virtualId
      }
      return null
    },
    load(id) {
      if (id === virtualId) {
        // Empty default export → Amplify.configure({}) is a harmless no-op and
        // getReviewApiUrl() returns null, so a review attempt fails visibly
        // (there is no mock/static fallback).
        return 'export default {}'
      }
      return null
    },
  }
}

export default defineConfig({
  plugins: [optionalAmplifyOutputs(), react()],
})
